#!/usr/bin/expect
set timeout 1
spawn gcc -g Partition_Array.c
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n" 
expect "Enter all elements of the array separated by spaces:\n"
send "4 9 4 1 2\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 4 2 7 8\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 8 1 4 9\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 1 3 8 4\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 1 2 3 5\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 1 2 5 4\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 1 2 4 5\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 3 9 1 5\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 9 3 5 1\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 9 3 2 1\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 9 3 1 5\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 4 1 2 5\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "5\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 1 4 2 5\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "4\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 4 1 2\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "4\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 1 4 2\n"
interact
sleep 2
puts "\n\n"
spawn ./a.out
expect "Enter the length of the array:\n"
send "4\n"
expect "Enter all elements of the array separated by spaces:\n"
send "4 1 2 4\n"
interact
